spring.application.name=effectifs
server.port=8090
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/police_db
spring.datasource.username=postgres
spring.datasource.password=JP@2023
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=false

spring.datasource.hikari.maximum-pool-size=10

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

sync.server.url=https://10.10.10.10:8090/api_pc_central/sync/batch
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.connection-timeout=9000000
spring.main.banner-mode=console


# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=police_db;encrypt=true;trustServerCertificate=true
# #spring.datasource.url=jdbc:sqlserver://host.docker.internal:1433;databaseName=police_db;encrypt=true;trustServerCertificate=true
# spring.datasource.username=sa
# spring.datasource.password=JP@2023
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
